### PR TITLE
Updating Changelog

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
Just updating the changelog from #69 to tag.

### Review
- @ascott1

### CODE REVIEW

**Comment by Scotchester** [comment]
Sorry I didn't catch this in the PR with the actual changes, but I don't think we should have these overrides in place by default. We'll still have the problem that any (third party) who runs the generator will be trying to use our Avenir Next webfonts right out of the gate.

I think we should comment out the `@import` and the `@webfont-` variables, and make people uncomment them to use them.

**Comment by KimberlyMunoz** [comment]
I thought the issue was that we wanted to separate out the CFPB brand variables in general and that includes the webfonts. 

Would it make more sense to link these in the `brand-palette.less` and then that can be commented out as necessary?

**Comment by Scotchester** [comment]
That was the main issue, yes, but also it doesn't make sense for that to be the default, because unless someone's got access to one of the domains on our whitelist, the fonts won't load, and they'll be making four useless HTTP requests.

I think they belong more in `cf-theme-overrides` than `brand-palette`. My reasoning is that `brand-palette` is more of a helper, where `cf-theme-overrides` is considered more essential. The `@import` for the webfonts might make more sense in `main.less`, actually?

**Comment by KimberlyMunoz** [comment]
I'll bug you on chat tomorrow and let's figure it out.

I like the idea to include `@import` in `main.less`. It makes it much more obvious to comment out or un-comment out.

**Comment by contolini** [comment]
LMK if you two need help hashing this out.

**Comment by KimberlyMunoz** [comment]
Ready for you to take a look, @Scotchester.

**Comment by Scotchester** [comment]
:+1: Thanks!

**Comment by Scotchester** [comment]
Please tag and release.

**Comment by KimberlyMunoz** [comment]
:+1: Done.

**Pull request merged**
