### PR TITLE
Stop importing normalize

### PR DESCRIPTION
**Pull request by contolini**
[cf-core now does it](https://github.com/cfpb/cf-core/blob/gh-pages/src/cf-core.less#L7-L8).

## Removals

- Normalize.css import rule in main.less

## Review

- @sephcoster

### CODE REVIEW

**Comment by Scotchester** [comment]
:+1:

**Comment by Scotchester** [comment]
Wait, :+1: retracted. Please update version numbers and changelog.

**Comment by contolini** [comment]
:star:

**Comment by Scotchester** [comment]
Thanks!

**Comment by Scotchester** [comment]
@contolini Please tag and release.

**Pull request merged**
