### PR TITLE
Adding setup.sh to build process

### PR DESCRIPTION
**Pull request by jimmynotjim**
It's 2015, all projects should be using a boot script for both developers and deployments to enjoy.

## Additions

- added `_setup.sh` template file
- updated generator to copy `_setup.sh` to `setup.sh`

## Removals

- removed `bower install` from `package.json` post install

## Changes

- replaced `npm install` with execution of `setup.sh`

## Testing

1. checkout branch and run `npm link`
1. create a temp test directory (outside this repo)
1. run `yo cf` in temp test directory

## Review

- @cfpb/front-end-team-admin 

## Preview

[Preview this PR without the whitespace changes](?w=0)

## Notes

- There's currently an eslint error that's outside the scope of this PR
  ```sh
  Running "lintjs:eslint" (lintjs) task

  Running "eslint:src" (eslint) task 
  Warning: Definition for rule 'no-unexpected-multiline' was not found. Use --force to continue.

  Aborted due to warnings.
```

### CODE REVIEW

**Comment by ascott1** [comment]
:+1: from me

**Comment by contolini** [comment]
@jimmynotjim [Bump grunt-eslint to `^16.0.0`](https://github.com/jimmynotjim/generator-cf/blob/97e3880d7b9fdfc7c5a93a25d9c3c86c215d1378/app/templates/_package.json#L32) to fix the eslint error.

**Comment by contolini** [comment]
And while you're in there, [delete the `yo` peer dependency](https://github.com/jimmynotjim/generator-cf/blob/97e3880d7b9fdfc7c5a93a25d9c3c86c215d1378/package.json#L38-L40).

**Comment by contolini** [comment]
:+1:

**Comment by jimmynotjim** [comment]
All completed. Since I've got a few PRs on this repo should we package them all for a single release?

**Comment by contolini** [comment]
@jimmynotjim Sounds good to me.

**Comment by Scotchester** [comment]
Anyone want to merge this via command line to fix the conflicts while Jimmy's out?

Not sure that it's a big deal if it waits until next week.

**Comment by contolini** [comment]
I can tackle it today. I noticed yesterday there's a broken link in [cfpb/front-end](https://github.com/cfpb/front-end/blob/master/build.md#building-your-projects-front-end) because this hasn't been merged yet.

**Comment by Scotchester** [comment]
Thanks @contolini!

**Comment by contolini** [comment]
Published as 1.1.0.

**Comment by jimmynotjim** [comment]
:+1: thanks for taking care of this

**Pull request merged**
