### PR TITLE
Updated contributing

### PR DESCRIPTION
**Pull request by jimmynotjim**
NPM requires that you symlink the component you need in the directory you plan on using it. Updated the directions to include that step.

## Changes

- Updated contributing section of README.md

## Testing

- Follow the instructions

### CODE REVIEW

**Comment by jimmynotjim** [comment]
It didn't work for me till I also symlinked in the other directory. See this comment [in the NPM docs](https://docs.npmjs.com/cli/link)

> Package linking is a two-step process.

**Comment by jimmynotjim** [comment]
Here's the error I get without symlinking in the test directory (this is a fresh directory)

screen shot 2018-03-02 at 2 12 06 pm

and after linking

screen shot 2018-03-02 at 2 13 00 pm

**Comment by Scotchester** [comment]
@jimmynotjim Is it possible you hadn't `npm install -g generator-cf`? I think if it's globally installed you don't need to link where you want to use it.

**Comment by Scotchester** [comment]
I was just able to test #143 without running `npm link generator-cf` in my test directory.

**Comment by jimmynotjim** [comment]
Ohhh weird, I removed the link, and made sure it was installed globally, but a brand new directory is saying I don't have it installed. There must be something else wrong with my setup, but it's not immediately clear what it is.

**Pull request merged**
