### PR TITLE
add new label style var

### PR DESCRIPTION
**Pull request by cfarm**
add new color variable for new form label element.

see https://github.com/cfpb/cf-forms/pull/38 for details

### CODE REVIEW

**Comment by jimmynotjim** [comment]
:+1: but now I have a thought, can we pull this file from the capital-framework repo rather than duplicating the work?

**Comment by Scotchester** [comment]
Yes, it would definitely be better to only maintain it in one place. I just now realized it was in capital-framework; I thought that the generator was the canonical source. I think we have some changes here in the generator repo that haven't made it to capital-framework.

I may have shared this idea before, but I've been wondering if we should create a "theming" mechanism for CF, so we could pull out this file, `brand-palette.less`, and `licensed-fonts.css` into their own repo that is clearly the canonical source.

**Comment by Scotchester** [comment]
Anyway, :+1: for now.

**Comment by ascott1** [comment]
> create a "theming" mechanism for CF, so we could pull out this file, brand-palette.less, and licensed-fonts.css into their own repo that is clearly the canonical source

+1 to this idea

**Comment by jimmynotjim** [comment]
Does it need to be yet another repo? Could it be in the parent CF repo once we figure out what does and doesn't need to be available through NPM?

**Comment by Scotchester** [comment]
That would be an immediate improvement, @jimmynotjim, but I think we want to get to the separate theme repo setup in the future, so that third parties grabbing CF don't all get our styling by default.

**Pull request merged**
