### PR TITLE
Fix requesting of CF components

### PR DESCRIPTION
**Pull request by contolini**
## Removals

- The ignore list is no longer required.

## Changes

- Update the GH endpoint used to retrieve list of components.

## Review

- @jimmynotjim 
- @Scotchester 
- @ascott1

### CODE REVIEW

**Comment by ascott1** [comment]
I'm still having the issue of components not populating the list, though looking at the code this seems like it should fix this problem.

What I've done:

- Pulled down this repo (which is `upstream` for me locally)
- Switched to the `upstream/bugfix/github-endpoint`
- ran `npm install` and `npm link`
- Created a new directory and ran `yo cf`

I also unlinked the directory, cleared the npm cache, and ran `npm link` again just to make sure there wasn't some funkiness there.

@contolini am I testing this PR correctly?

**Comment by contolini** [comment]
@ascott1 Hmmm, that's weird. It's possible `npm link` isn't working for some reason. Try editing the opening [log statement](https://github.com/cfpb/generator-cf/blob/master/app/index.js#L54-L57) and see if your edits appear when you run `yo cf`.

**Comment by ascott1** [comment]
@contolini I can edit the prompts view the updates when running the generator, so `npm link` is definitely working. I updated to the most recent version of 4.2 and I'm only prompted to install "Type-testing," but all of the components seem to install. The same is true in 5.6

**Comment by jimmynotjim** [comment]
You need to run `npm link generator-cf` in your project dir you want the generator to run in. 

> Next, in some other location, `npm link package-name` will create a symlink from the local `node_modules` folder to the global symlink.

https://docs.npmjs.com/cli/link

**Comment by contolini** [comment]
@ascott1 See if that fixes it for you but my understanding is that npm linking in the project directory isn't necessary because generators are installed globally (not locally).

**Comment by jimmynotjim** [comment]
:+1:

**Comment by ascott1** [comment]
Let's merge. I think we've determined that the issue I'm having is unique to my environment and I'm hopeful that installing from npm will be the fix (or if not, we can make an additional fix in a future pull request or I can document what the issue was for me locally)

**Pull request merged**
